'use strict';
const menuButton=document.querySelector('.menu-toggle');
menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Menü schließen':'Menü öffnen');document.querySelector('#mobile-nav').hidden=!open;});
document.querySelectorAll('#mobile-nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#mobile-nav').hidden=true;menuButton.setAttribute('aria-expanded','false');}));

const icons={leaf:'<path d="M20 4C8 2 2 9 7 16s14 1 13-12Z"/><path d="M4 21 16 9M9 16l-1-5m5 1 4 1"/>',heart:'<path d="M12 21 3 12C-3 5 6-2 12 6c6-8 15-1 9 6Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',waves:'<path d="M2 7c4-5 6 5 10 0s6 5 10 0M2 12c4-5 6 5 10 0s6 5 10 0M2 17c4-5 6 5 10 0s6 5 10 0"/>',phone:'<path d="M6 3H3c-1 9 9 19 18 18v-3l-5-3-2 2c-3-1-6-4-7-7l2-2z"/>',home:'<path d="m3 10 9-8 9 8M5 9v12h14V9M9 21v-8h6v8"/>',chat:'<path d="M21 11a9 9 0 0 1-9 9H3l1-5A9 9 0 1 1 21 11Z"/><path d="M8 10h8m-8 4h5"/>',check:'<path d="m5 12 4 4 10-10"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',shield:'<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6Z"/><path d="m8 12 3 3 5-6"/>'};
const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.heart}</svg>`;
const escapeHTML=(value)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

document.querySelector('#page-sections').innerHTML=`
<section class="entry-cards section-wrap" aria-label="Wie können wir Sie unterstützen?">
  <article class="entry-card entry-card-featured"><div class="card-top">${icon('heart')}<span>HILFE IM MOMENT</span></div><h3>Ein Mensch ist<br>verstorben.</h3><p>Was ist jetzt wichtig? Wir helfen Ihnen, die ersten Schritte zu sortieren.</p><button class="text-button" data-start="trauerfall">Ich brauche Unterstützung <span aria-hidden="true">+</span></button></article>
  <article class="entry-card"><div class="card-top">${icon('leaf')}<span>FÜR MORGEN VORSORGEN</span></div><h3>Heute für später<br>entscheiden.</h3><p>Eigene Wünsche festhalten. Und den Menschen, die bleiben, Sicherheit geben.</p><button class="text-button" data-start="vorsorge">Vorsorge kennenlernen <span aria-hidden="true">+</span></button></article>
  <article class="entry-card"><div class="card-top">${icon('chat')}<span>ERST EINMAL ANKOMMEN</span></div><h3>Ich möchte mich<br>in Ruhe informieren.</h3><p>Welche Möglichkeiten gibt es? Finden Sie heraus, was sich für Sie richtig anfühlt.</p><a class="text-button" href="#wege">Möglichkeiten entdecken <span aria-hidden="true">+</span></a></article>
</section>
<section class="first-help section-wrap"><div class="first-help-title"><p class="eyebrow">WENN EIN TODESFALL EINGETRETEN IST</p><h2>Was jetzt<br>wirklich zählt.</h2><a href="tel:+49203582448" class="help-phone">${icon('phone')} 0203 · 58 24 48</a></div><ol class="first-help-list"><li><span>01</span><div><h3>Den Tod ärztlich feststellen lassen</h3><p>Zu Hause kontaktieren Sie die Hausarztpraxis oder den ärztlichen Bereitschaftsdienst unter <a href="tel:116117">116 117</a>. In einer Einrichtung hilft das dortige Personal.</p></div></li><li><span>02</span><div><h3>Rufen Sie uns an. Wir hören Ihnen zu.</h3><p>Sie müssen am Telefon noch nichts entscheiden. Wir klären mit Ihnen, was als Nächstes gebraucht wird.</p></div></li><li><span>03</span><div><h3>Die nötigen Unterlagen zusammenstellen</h3><p><strong>Wir helfen bei fehlenden Unterlagen.</strong> Wir besprechen mit Ihnen, welche Dokumente benötigt werden.</p><button class="text-button" data-info="documents">Dokumentenliste öffnen <span aria-hidden="true">+</span></button></div></li></ol></section>
<section class="journey-banner"><div class="journey-copy"><p class="eyebrow light">IHR PERSÖNLICHER BEGLEITER</p><h2>Viele Fragen.<br><em>Ein behutsamer Weg.</em></h2><p>Mit wenigen Fragen ordnen wir, was Ihnen wichtig ist. <strong>Sie bestimmen das Tempo.</strong> Ihre Antworten bilden die Grundlage für ein persönliches Gespräch.</p><button class="button button-cream" data-start>Gespräch in Ruhe vorbereiten</button><span class="small-note">Etwa 3–5 Minuten · Sie legen sich noch nicht fest</span></div><div class="journey-preview" aria-hidden="true"><div class="preview-top"><span>EIN SCHRITT NACH DEM ANDEREN</span><span>02 / 06</span></div><div class="preview-progress"><i></i></div><p>Was fühlt sich<br>für Sie richtig an?</p><div class="preview-option">${icon('leaf')} Ein Abschied in der Natur <span>○</span></div><div class="preview-option selected">${icon('chat')} Ich weiß es noch nicht <span>✓</span></div><small>Sie müssen heute noch nichts festlegen.</small></div></section>
<section class="ways section-wrap" id="wege" aria-labelledby="ways-title">
  <div class="section-heading"><div><p class="eyebrow">WEGE DES ABSCHIEDS</p><h2 id="ways-title">Ein Abschied, der zu<br><em>diesem Leben passt.</em></h2></div><p>Ein vertrauter Ort, die Nähe zur Natur oder die Weite des Meeres: Finden Sie in Ruhe heraus, was Ihnen wichtig ist.</p></div>
  <p class="ways-introduction">Grundsätzlich wird zwischen Erd- und Feuerbestattung unterschieden. <strong>Baum- und Seebestattungen sind Formen der Urnenbeisetzung</strong> nach einer Einäscherung.</p>
  <div class="burial-gallery">
    <article class="burial-card"><button class="burial-image-button" data-info="earth" aria-label="Mehr zur Erdbestattung"><img src="assets/erdbestattung.webp" alt="Feine Maserung von Eichenholz mit einem weißen Blütenblatt in warmer Makroaufnahme" width="1440" height="960" loading="lazy"><span class="material-caption">01 — HOLZ & GEBORGENHEIT</span></button><div class="burial-card-body"><p class="eyebrow">EIN VERTRAUTER ORT</p><h3>Erdbestattung</h3><p>Die Beisetzung im Sarg auf einem Friedhof. Ein fester Ort, den Sie besuchen und mit Erinnerungen verbinden können.</p><dl class="burial-facts"><div><dt>Beisetzung</dt><dd>Im Sarg</dd></div><div><dt>Erinnerungsort</dt><dd>Grab auf dem Friedhof</dd></div></dl><button class="text-button" data-info="earth">Die Erdbestattung kennenlernen <span aria-hidden="true">+</span></button></div></article>
    <article class="burial-card"><button class="burial-image-button" data-info="fire" aria-label="Mehr zur Feuerbestattung"><img src="assets/feuerbestattung.webp" alt="Sanft gerundeter Rand einer elfenbeinfarbenen Keramikurne, aus nächster Nähe fotografiert" width="1440" height="960" loading="lazy"><span class="material-caption">02 — KERAMIK & ERINNERUNG</span></button><div class="burial-card-body"><p class="eyebrow">VIELE PERSÖNLICHE MÖGLICHKEITEN</p><h3>Feuerbestattung</h3><p>Nach der Einäscherung wird die Asche in einer Urne beigesetzt. Auf dem Friedhof stehen unterschiedliche Grabformen zur Wahl.</p><dl class="burial-facts"><div><dt>Beisetzung</dt><dd>In einer Urne</dd></div><div><dt>Erinnerungsort</dt><dd>Zum Beispiel Urnengrab oder Kolumbarium</dd></div></dl><button class="text-button" data-info="fire">Die Feuerbestattung kennenlernen <span aria-hidden="true">+</span></button></div></article>
    <article class="burial-card"><button class="burial-image-button" data-info="tree" aria-label="Mehr zur Baumbestattung"><img src="assets/baumbestattung.webp" alt="Samtiges grünes Moos auf strukturierter Baumrinde im warmen Sonnenlicht" width="1440" height="960" loading="lazy"><span class="material-caption">03 — MOOS & VERBUNDENHEIT</span></button><div class="burial-card-body"><p class="eyebrow">DER NATUR NAH</p><h3>Baumbestattung</h3><p>Eine Urnenbeisetzung an den Wurzeln eines Baumes. Möglich in einem Bestattungswald oder auf einem geeigneten Friedhof.</p><dl class="burial-facts"><div><dt>Beisetzung</dt><dd>Urne im Wurzelbereich</dd></div><div><dt>Erinnerungsort</dt><dd>Ein ausgewählter Baum</dd></div></dl><button class="text-button" data-info="tree">Die Baumbestattung kennenlernen <span aria-hidden="true">+</span></button></div></article>
    <article class="burial-card"><button class="burial-image-button" data-info="sea" aria-label="Mehr zur Seebestattung"><img src="assets/seebestattung.webp" alt="Durchscheinende kleine Meereswelle mit goldenen Lichtreflexen in Makroaufnahme" width="1440" height="960" loading="lazy"><span class="material-caption">04 — WASSER & WEITE</span></button><div class="burial-card-body"><p class="eyebrow">DEM MEER VERBUNDEN</p><h3>Seebestattung</h3><p>Eine wasserlösliche Urne wird auf See beigesetzt. Auf Wunsch und je nach Angebot können Angehörige den Abschied an Bord begleiten.</p><dl class="burial-facts"><div><dt>Beisetzung</dt><dd>Urne im Meer</dd></div><div><dt>Erinnerungsort</dt><dd>Das Meer, ohne Grabstätte an Land</dd></div></dl><button class="text-button" data-info="sea">Die Seebestattung kennenlernen <span aria-hidden="true">+</span></button></div></article>
  </div>
  <details class="comparison"><summary>Was unterscheidet die Bestattungsarten?</summary><div class="table-scroll" role="region" aria-label="Vergleich der Bestattungsarten" tabindex="0"><table><caption>Eine erste Orientierung. Die Möglichkeiten vor Ort besprechen wir persönlich.</caption><thead><tr><th scope="col">Ihre Frage</th><th scope="col">Erdbestattung</th><th scope="col">Feuerbestattung auf dem Friedhof</th><th scope="col">Baumbestattung</th><th scope="col">Seebestattung</th></tr></thead><tbody><tr><th scope="row">Ist eine Einäscherung nötig?</th><td>Nein</td><td>Ja</td><td>Ja</td><td>Ja</td></tr><tr><th scope="row">Gibt es einen Ort für Besuche?</th><td>Die Grabstätte</td><td>Das Urnengrab oder die Urnennische</td><td>Den Baum oder Wald</td><td>Keine Grabstätte an Land</td></tr><tr><th scope="row">Wer kümmert sich um die Grabpflege?</th><td>Abhängig von der Grabart</td><td>Abhängig von der Grabart</td><td>Abhängig vom Friedhof oder Wald</td><td>Keine Grabpflege erforderlich</td></tr><tr><th scope="row">Ist eine Trauerfeier möglich?</th><td>Ja, individuell gestaltbar</td><td>Ja, vor oder nach der Einäscherung</td><td>Je nach Ort und Rahmen</td><td>Je nach Reederei und Angebot</td></tr></tbody></table></div></details>
  <div class="orientation-note">${icon('chat')}<p><strong>Sie dürfen noch unsicher sein.</strong> Ein persönliches Gespräch hilft, Möglichkeiten einzuordnen.</p><button class="text-button" data-start>Gemeinsam Klarheit finden <span aria-hidden="true">+</span></button></div>
</section>
<section class="farewell"><div class="candle-image"><img src="assets/kerze.webp" alt="Die sanfte Flamme einer elfenbeinfarbenen Kerze, aus nächster Nähe fotografiert" width="1400" height="933" loading="lazy"><span class="photo-number">LICHT FÜR DIE ERINNERUNG</span></div><div class="farewell-copy"><p class="eyebrow">RAUM FÜR DAS, WAS BLEIBT</p><h2>Ein Lieblingslied.<br>Eine Geschichte.<br><em>Ein ganz eigener Abschied.</em></h2><p>Unsere eigene Trauerhalle und unsere Abschiedsräume geben Ihren Erinnerungen einen Platz. Mit Musik, Blumen und Worten, die zu diesem einen Menschen gehören.</p><button class="text-button" data-info="farewell">Den Abschied persönlich gestalten <span aria-hidden="true">+</span></button></div></section>
<section class="accompaniment section-wrap" id="begleitung" aria-labelledby="accompaniment-title"><div class="section-heading"><div><p class="eyebrow">WAS WIR IHNEN ABNEHMEN</p><h2 id="accompaniment-title">Von der ersten Frage<br><em>bis zum Abschied.</em></h2></div><p>Sie bringen Ihre Fragen und Wünsche mit.<br>Wir helfen, daraus einen stimmigen Weg zu machen.</p></div><ol class="accompaniment-steps"><li><span class="step-number">01</span><h3>Zuhören und ordnen</h3><p>Wir klären, was gerade gebraucht wird, beantworten erste Fragen und besprechen die nächsten Schritte.</p><span class="step-emphasis">Ein Anruf genügt für den Anfang.</span></li><li><span class="step-number">02</span><h3>Gemeinsam planen</h3><p>Bestattungsform, Ort, Gestaltung und Kosten: Wir erklären die Möglichkeiten und halten Ihre Wünsche fest.</p><span class="step-emphasis">Mit einem nachvollziehbaren Angebot.</span></li><li><span class="step-number">03</span><h3>Den Abschied gestalten</h3><p>Wir koordinieren Termine, Formalitäten und die Trauerfeier. Sie entscheiden, was Sie selbst beitragen möchten.</p><span class="step-emphasis">So persönlich, wie Sie es wünschen.</span></li><li><span class="step-number">04</span><h3>Weiter für Sie da sein</h3><p>Auch nach der Beisetzung dürfen Fragen bleiben. Bei Bedarf vermitteln wir Kontakte für weitere Unterstützung.</p><span class="step-emphasis">Weil Begleitung nicht abrupt endet.</span></li></ol></section>
<section class="costs section-wrap" id="kosten"><div><p class="eyebrow">KLARHEIT GIBT SICHERHEIT</p><h2>Über Geld darf man sprechen.<br><em>Auch jetzt.</em></h2><p>Die Kosten hängen von der Bestattungsform, dem Ort und Ihren Wünschen ab. Wir erklären Ihnen die einzelnen Positionen. <strong>Bevor Sie einen Auftrag erteilen.</strong></p><button class="text-button" data-info="costs">Wie sich die Kosten zusammensetzen <span aria-hidden="true">+</span></button></div><div class="cost-breakdown"><div><span>01</span><strong>Unsere Begleitung</strong><p>Beratung, Organisation, Versorgung und Überführung</p></div><div><span>02</span><strong>Ihr persönlicher Abschied</strong><p>Sarg oder Urne, Blumen, Musik und Trauerfeier</p></div><div><span>03</span><strong>Weitere Leistungen und Gebühren</strong><p>Zum Beispiel Friedhof, Krematorium und Urkunden</p></div><small>Ein verbindliches Angebot entsteht im persönlichen Gespräch.</small></div></section>
<section class="provision section-wrap" id="vorsorge"><span class="provision-symbol">${icon('leaf')}</span><div><p class="eyebrow">BESTATTUNGSVORSORGE</p><h2>Ein gutes Gefühl,<br><em>etwas geregelt zu haben.</em></h2><p>Mit einer Bestattungsvorsorge halten Sie fest, <strong>was Ihnen für Ihren eigenen Abschied wichtig ist.</strong> Das gibt Ihren Angehörigen später Orientierung.</p><ul class="provision-list"><li>Bestattungsform und Ort in Ruhe besprechen</li><li>Persönliche Wünsche für die Trauerfeier festhalten</li><li>Möglichkeiten der finanziellen Absicherung klären</li></ul></div><button class="button button-outline" data-start="vorsorge">Über meine Vorsorge sprechen</button></section>
<section class="about section-wrap" id="ueber-uns"><div class="about-statement"><p class="eyebrow">KRETSCHMER BESTATTUNGEN</p><h2>In Duisburg verwurzelt.<br><em>Mit Menschen verbunden.</em></h2><p>1963 von Heinrich Kretschmer gegründet, wird unser Familienunternehmen heute von Martin und Ulrich Kretschmer geführt. Was uns trägt, ist die Nähe zu den Menschen hier.</p><p>Wir nehmen Ihnen Organisatorisches ab und schaffen Raum für Ihren Abschied. In unserem Haus, auf Wunsch bei Ihnen zu Hause und in der Zeit nach der Beisetzung.</p><a class="text-button" href="https://www.kretschmer-duisburg.de/ueber-kretschmer" target="_blank" rel="noopener noreferrer">Das Team auf der Originalwebsite kennenlernen <span aria-hidden="true">+</span></a></div><div class="heritage"><span class="heritage-k">k.</span><span>AN IHRER SEITE</span><strong>seit 1963</strong><div class="heritage-line"></div><p>Familienunternehmen.<br>Meisterbetrieb.<br>Ein Teil von Duisburg.</p></div></section>
<section class="credentials section-wrap" id="qualitaet" aria-labelledby="credentials-title"><div class="credentials-heading"><p class="eyebrow">QUALIFIKATION UND ENGAGEMENT</p><h2 id="credentials-title">Vertrauen braucht<br><em>eine gute Grundlage.</em></h2><p>Fachwissen, Verantwortung und die Verbundenheit mit unserer Region prägen unsere Arbeit.</p></div><div class="credential-grid"><article class="credential"><div class="credential-seal" aria-hidden="true">${icon('shield')}<span>MEISTER-<br>BETRIEB</span></div><h3>Bestattermeister<br>im Team</h3><p>Martin Kretschmer ist Bestattermeister; Nadine Trautmann ist Bestattermeisterin. Beide bringen ihr Fachwissen in die Begleitung ein.</p><a href="https://www.kretschmer-duisburg.de/ueber-kretschmer" target="_blank" rel="noopener noreferrer">Qualifikation ansehen</a></article><article class="credential"><div class="credential-seal" aria-hidden="true"><strong>HWK</strong><span>DÜSSELDORF</span></div><h3>Mitglied der<br>Handwerkskammer</h3><p>Das Unternehmen führt die Handwerkskammer Düsseldorf als zuständige Kammer im Impressum auf.</p><a href="https://www.kretschmer-duisburg.de/impressum" target="_blank" rel="noopener noreferrer">Kammermitgliedschaft ansehen</a></article><article class="credential"><div class="credential-seal" aria-hidden="true"><strong>NRW</strong><span>IM VERBAND<br>ENGAGIERT</span></div><h3>Verantwortung<br>in der Region</h3><p>Martin Kretschmer ist Vorsitzender des Kreisverbands Duisburg/Wesel im Bestatterverband NRW.</p><a href="https://www.bestatter-nrw.de/de/der-verband/bezirksverbaende/kreisverband-duisburg--wesel/" target="_blank" rel="noopener noreferrer">Verbandsarbeit ansehen</a></article></div></section>
<section class="aftercare section-wrap" id="trauerbegleitung" aria-labelledby="aftercare-title"><div class="aftercare-image"><img src="assets/tau.webp" alt="Ein klarer Tautropfen auf einem Blatt im sanften Morgenlicht" width="1400" height="933" loading="lazy"><span>RAUM FÜR DAS, WAS SIE BEWEGT.</span></div><div class="aftercare-copy"><p class="eyebrow">AUCH NACH DEM ABSCHIED</p><h2 id="aftercare-title">Trauer braucht<br><em>keinen Zeitplan.</em></h2><p>Manchmal hilft ein Gespräch. Manchmal eine gemeinsame Erinnerung. <strong>Sie müssen Ihren Weg nicht allein finden.</strong> Wir vermitteln auf Wunsch Kontakte zur Trauerbegleitung.</p><div class="aftercare-resources"><button data-info="grief"><span>Unterstützung finden</span><small>Gespräche, Gruppen und Anlaufstellen in Duisburg</small><b aria-hidden="true">+</b></button><button data-info="children"><span>Mit Kindern über den Abschied sprechen</span><small>Raum für Fragen, Gefühle und kleine Rituale</small><b aria-hidden="true">+</b></button><button data-info="condolence"><span>Für einen trauernden Menschen da sein</span><small>Persönliche Worte und konkrete Unterstützung</small><b aria-hidden="true">+</b></button></div></div></section>
<section class="faq section-wrap" id="fragen"><div><p class="eyebrow">ANTWORTEN, DIE ENTLASTEN</p><h2>Fragen, die Sie<br><em>beschäftigen könnten.</em></h2><p>Jede Frage darf gestellt werden.</p></div><div class="faq-items"><details><summary>Muss ich mich sofort für alles entscheiden?</summary><p>Nein. Im ersten Gespräch ordnen wir gemeinsam, was zeitnah geklärt werden muss und wofür noch Zeit bleibt. Sie können Wünsche offenlassen und Fragen mitbringen.</p></details><details><summary>Kann ich den Abschied selbst mitgestalten?</summary><p>Ja. Ein Lieblingslied, persönliche Erinnerungen, Blumen oder eigene Worte können Teil der Trauerfeier sein. Wir besprechen mit Ihnen, was möglich ist und sich stimmig anfühlt.</p></details><details><summary>Was ist, wenn wichtige Unterlagen fehlen?</summary><p>Rufen Sie trotzdem an. Wir besprechen, welche Dokumente benötigt werden und wie fehlende Unterlagen beschafft werden können.</p></details><details><summary>Was passiert nach der digitalen Vorbereitung?</summary><p>Sie sehen Ihre Wünsche in einer Zusammenfassung und können sie für ein Gespräch speichern. Diese Website ist eine Pitch-Vorschau: Angaben werden nicht versendet und es wird kein Termin gebucht.</p></details><details><summary>Wo finde ich Unterstützung in meiner Trauer?</summary><p>Trauer hat kein festes Tempo. Kretschmer kann Kontakte zur Trauerbegleitung vermitteln. Weitere Anregungen finden Sie im <a href="https://www.kretschmer-duisburg.de/service" target="_blank" rel="noopener noreferrer">Ratgeber auf der Originalwebsite</a>.</p></details></div></section>
<section class="contact-section" id="kontakt"><p class="eyebrow light">MANCHMAL BRAUCHT ES ERST EINMAL EINEN MENSCHEN.</p><h2>Wir hören Ihnen zu.</h2><a class="contact-number" href="tel:+49203582448">0203 · 58 24 48</a><p>Tag und Nacht. Auch am Wochenende.</p><span class="contact-divider">oder ganz in Ruhe</span><button class="button button-cream" data-start>Ein persönliches Gespräch vorbereiten</button></section>`;

document.querySelector('#page-footer').innerHTML=`<footer class="footer section-wrap"><div class="footer-top"><a class="brand" href="#"><span class="brand-mark" aria-hidden="true">k.</span><span><strong>Kretschmer</strong><small>BESTATTUNGEN · DUISBURG</small></span></a><p>Weil jeder Abschied<br>ein Teil des Lebens ist.</p><div><span class="footer-label">HAUPTGESCHÄFT</span><p>Theodor-Heuss-Straße 122<br>47167 Duisburg</p><a href="https://www.google.com/maps/search/?api=1&query=Kretschmer+Theodor-Heuss-Stra%C3%9Fe+122+Duisburg" target="_blank" rel="noopener noreferrer">Anfahrt ansehen</a></div><div><span class="footer-label">PERSÖNLICHER KONTAKT</span><a href="tel:+49203582448">0203 · 58 24 48</a><a href="mailto:info@kretschmer-duisburg.de">info@kretschmer-duisburg.de</a><button class="inline-button" data-info="locations">Alle Standorte</button></div></div><div class="footer-bottom"><span>Unabhängiger Website-Entwurf · Pitch 2026</span><div><a href="#qualitaet">Qualifikation</a><button class="inline-button" data-info="legal">Zum Entwurf</button><button class="inline-button" data-info="privacy">Datenschutz</button><a href="https://www.kretschmer-duisburg.de/impressum" target="_blank" rel="noopener noreferrer">Original-Impressum</a></div></div><p class="pitch-note">Konzept auf Grundlage der <a href="https://www.kretschmer-duisburg.de/" target="_blank" rel="noopener noreferrer">Kretschmer-Website</a>. Keine offizielle Website des Bestattungshauses. Der Beratungsflow ist eine Vorschau; es werden keine Anfragen versendet.</p></footer>`;

const infoData={
 grief:{label:'UNTERSTÜTZUNG IN DER TRAUER',title:'Es darf jemanden geben, der zuhört.',body:'<p>Wer sich Unterstützung wünscht, kann sich an Trauerbegleiter, Seelsorge, Trauergruppen oder ein Trauercafé wenden. Kretschmer hilft dabei, Kontakte zu finden.</p><h3>Anlaufstellen in Duisburg</h3><p>Der Ratgeber des Bestattungshauses nennt unter anderem die Caritas Duisburg, die Katholische Stadtkirche und das Hospiz Bethesda. Dort können Sie nach aktuellen Angeboten fragen.</p><a class="text-button" href="https://www.kretschmer-duisburg.de/service" target="_blank" rel="noopener noreferrer">Anlaufstellen im Ratgeber ansehen</a>'},
 children:{label:'KINDER BEIM ABSCHIED BEGLEITEN',title:'Fragen dürfen immer wiederkommen.',body:'<p>Kinder brauchen verständliche, ehrliche Antworten und Menschen, die ihre Gefühle ernst nehmen. Sie müssen nicht auf jede Frage sofort eine Antwort haben.</p><ul><li>Nehmen Sie sich Zeit zum Zuhören.</li><li>Sprechen Sie klar und dem Alter entsprechend über den Tod.</li><li>Ein gemaltes Bild, eine Erinnerungskiste oder ein gemeinsames Ritual können einen eigenen Zugang zum Abschied geben.</li><li>Lassen Sie das Kind mitentscheiden, ob und wie es sich beteiligen möchte.</li></ul><p>Im Ratgeber finden Sie weitere Anregungen und Bücher für unterschiedliche Altersgruppen.</p><a class="text-button" href="https://www.kretschmer-duisburg.de/service" target="_blank" rel="noopener noreferrer">Trost für Kinder im Ratgeber</a>'},
 condolence:{label:'MITGEFÜHL ZEIGEN',title:'Nähe braucht keine perfekten Worte.',body:'<p>Eine persönliche Erinnerung oder ein ehrlicher Satz können mehr bedeuten als eine fertige Floskel. Sie dürfen sagen, dass Ihnen die Worte fehlen.</p><h3>Hilfe darf konkret sein</h3><p>Bieten Sie zum Beispiel an, einen Einkauf zu übernehmen, gemeinsam spazieren zu gehen oder einfach zuzuhören. Fragen Sie, was gerade gebraucht wird, und respektieren Sie auch den Wunsch nach Ruhe.</p><a class="text-button" href="https://www.kretschmer-duisburg.de/service" target="_blank" rel="noopener noreferrer">Weitere Anregungen zur Kondolenz</a>'},
 documents:{label:'FÜR DAS ERSTE GESPRÄCH',title:'Was Sie bereitlegen können.',body:'<p>Bringen Sie mit, was Ihnen bereits vorliegt. Fehlende Unterlagen müssen Sie nicht allein beschaffen.</p><ul><li>Personalausweis oder Reisepass der verstorbenen Person</li><li>Ärztliche Todesbescheinigung (Totenschein)</li><li>Je nach Familienstand: Geburts- oder Eheurkunde, gegebenenfalls Scheidungsurteil oder Sterbeurkunde der Partnerin bzw. des Partners</li><li>Krankenversicherungskarte, Renten- und Versicherungsunterlagen</li><li>Falls vorhanden: Vorsorgevertrag und Unterlagen zu einer Grabstätte</li></ul><p class="info-footnote">Welche Dokumente in Ihrem Fall nötig sind, klären wir persönlich.</p><a class="text-button" href="https://www.kretschmer-duisburg.de/trauerfall" target="_blank" rel="noopener noreferrer">Vollständige Liste auf der Originalwebsite</a>'},
 earth:{label:'WEGE DES ABSCHIEDS',title:'Die Erdbestattung.',body:'<p>Bei einer Erdbestattung wird der Sarg auf einem Friedhof beigesetzt. Eine feste Grabstätte kann ein vertrauter Ort für Besuche und Erinnerungen sein.</p><h3>Was wir gemeinsam klären</h3><ul><li>Welche Friedhöfe und Grabarten infrage kommen</li><li>Ob bereits eine Familiengrabstätte vorhanden ist</li><li>Wie die Pflege des Grabes gestaltet werden soll</li></ul><p>Die konkreten Möglichkeiten und Gebühren hängen vom jeweiligen Friedhof ab.</p>',start:'Erdbestattung'},
 fire:{label:'WEGE DES ABSCHIEDS',title:'Die Feuerbestattung.',body:'<p>Nach der Einäscherung wird die Asche in einer Urne beigesetzt. Auf Friedhöfen stehen unterschiedliche Grabformen zur Verfügung; auch Baum- und Seebestattungen setzen eine Einäscherung voraus.</p><h3>Raum für persönliche Wünsche</h3><p>Eine Trauerfeier kann vor oder nach der Einäscherung geplant werden. Wir besprechen den Ort der Beisetzung und die Möglichkeiten der Abschiednahme gemeinsam.</p>',start:'Feuerbestattung'},
 tree:{label:'WEGE DES ABSCHIEDS',title:'Die Baumbestattung.',body:'<p>Die Urne wird im Wurzelbereich eines Baumes beigesetzt. Möglich ist dies in dafür vorgesehenen Bestattungswäldern und auf geeigneten Friedhöfen.</p><h3>Mit der Natur verbunden</h3><p>Die Bedingungen für Kennzeichnung, Blumenschmuck und Pflege unterscheiden sich je nach Ort. Wir besprechen, welcher Platz zu Ihren Vorstellungen passt.</p>',start:'Baumbestattung'},
 sea:{label:'WEGE DES ABSCHIEDS',title:'Die Seebestattung.',body:'<p>Eine wasserlösliche Urne wird auf See beigesetzt. Je nach Angebot können Angehörige die Beisetzung an Bord begleiten oder einen stillen Abschied wählen.</p><h3>Ein anderer Ort der Erinnerung</h3><p>Hier gibt es keine klassische Grabstätte. Gemeinsam klären wir Seegebiet, Begleitung und Ablauf der Zeremonie.</p>',start:'Seebestattung'},
 farewell:{label:'PERSÖNLICH ABSCHIED NEHMEN',title:'Was diesen Menschen ausgemacht hat.',body:'<p>Ein Abschied darf Persönlichkeit zeigen. Unsere eigene Trauerhalle und separate Abschiedsräume ermöglichen einen persönlichen Rahmen.</p><ul><li>Musik, die mit Erinnerungen verbunden ist</li><li>Persönliche Worte oder eine begleitete Trauerrede</li><li>Blumen, Fotos und vertraute Gegenstände</li><li>Eine stille Abschiednahme im kleinen Kreis</li></ul><p>Sie entscheiden, wie viel Sie selbst gestalten möchten. Wir helfen bei der Organisation.</p>',start:'offen'},
 costs:{label:'TRANSPARENT VON ANFANG AN',title:'Kosten verstehen. In Ruhe entscheiden.',body:'<p>Der Gesamtbetrag ergibt sich aus den gewählten Leistungen sowie den Gebühren von Friedhof, Krematorium und weiteren Stellen. Deshalb nennt dieser Entwurf keinen pauschalen Endpreis.</p><p>In der Beratung lassen sich notwendige Leistungen und persönliche Wünsche getrennt betrachten. Sprechen Sie auch einen finanziellen Rahmen offen an.</p><p>Informationen zu Finanzierungsmöglichkeiten erhalten Sie direkt beim Bestattungshaus. Ein Angebot wird individuell erstellt.</p><a class="text-button" href="https://www.kretschmer-duisburg.de/trauerfall#bestattungskosten" target="_blank" rel="noopener noreferrer">Kosteninformationen auf der Originalwebsite</a>'},
 locations:{label:'IN DUISBURG FÜR SIE DA',title:'Orte für ein persönliches Gespräch.',body:'<ul class="location-list"><li><strong>Hauptgeschäft</strong><br>Theodor-Heuss-Straße 122 · 47167 Duisburg<br><a href="tel:+49203582448">0203 / 58 24 48</a></li><li><strong>Zweigstelle Lehrerstraße</strong><br>Lehrerstraße 1 · 47167 Duisburg</li><li><strong>Am evangelischen Friedhof Marxloh</strong><br>Kaiser-Friedrich-Straße 108 · 47169 Duisburg</li><li><strong>Wintgensstraße</strong><br>Wintgensstraße 112 · 47058 Duisburg<br><a href="tel:+49203330186">0203 / 33 01 86</a></li></ul><p>Bitte stimmen Sie Ihren Besuch vorher telefonisch ab.</p>'},
 legal:{label:'ÜBER DIESE WEBSITE',title:'Ein Konzept für mehr Nähe.',body:'<p>Diese Website ist ein unabhängiger Design- und Funktionsentwurf für einen Pitch. Sie ist weder die offizielle Website von Kretschmer Bestattungen noch ein beauftragter Buchungsdienst.</p><p>Die Unternehmensinformationen wurden am 5. Oktober 2026 anhand von <a href="https://www.kretschmer-duisburg.de/" target="_blank" rel="noopener noreferrer">kretschmer-duisburg.de</a> zusammengestellt. Die sieben Makrofotografien wurden eigens mit KI erstellt; sie zeigen keine tatsächlichen Räume oder Produkte des Unternehmens.</p><p>Der Beratungsflow simuliert eine Gesprächsanfrage. Es entsteht kein Auftrag und kein gebuchter Termin.</p>'},
 privacy:{label:'IHRE ANGABEN IN DIESER VORSCHAU',title:'Persönliches bleibt bei Ihnen.',body:'<p>Formulareingaben werden nur im Arbeitsspeicher dieses geöffneten Browserfensters verarbeitet. Sie werden nicht an das Bestattungshaus gesendet und nicht in einer Datenbank oder im Browser-Speicher gespeichert. Beim Neuladen gehen sie verloren.</p><p>Bitte verwenden Sie zum Ausprobieren Beispieldaten. Mit „Neu beginnen“ können Sie die aktuellen Angaben löschen. Ein Download speichert Ihre Zusammenfassung als Textdatei auf Ihrem Gerät.</p><p>Diese Website nutzt keine Analyse- oder Marketingdienste. Bilder und Schriften werden lokal ausgeliefert. Der Hostinganbieter kann technische Zugriffsdaten wie IP-Adresse und Zeitpunkt verarbeiten. Externe Links öffnen Angebote anderer Anbieter.</p><p>Für einen produktiven Einsatz müssen Verantwortlicher, Hosting und tatsächliche Datenverarbeitung in einer vollständigen Datenschutzerklärung dokumentiert werden.</p>'}
};
const burialImages={
 earth:{src:'assets/erdbestattung.webp',alt:'Eichenholz und weißes Blütenblatt im warmen Licht',name:'Erdbestattung'},
 fire:{src:'assets/feuerbestattung.webp',alt:'Detail einer elfenbeinfarbenen Keramikurne',name:'Feuerbestattung'},
 tree:{src:'assets/baumbestattung.webp',alt:'Moos auf strukturierter Baumrinde',name:'Baumbestattung'},
 sea:{src:'assets/seebestattung.webp',alt:'Sonnenlicht auf einer kleinen Meereswelle',name:'Seebestattung'}
};
const infoDialog=document.querySelector('#information');
function showInfo(key){const d=infoData[key];if(!d)return;document.querySelector('#info-content').innerHTML=`${burialImages[key]?`<img class="info-macro" src="${burialImages[key].src}" alt="${burialImages[key].alt}" width="1440" height="960">`:""}<p class="eyebrow">${d.label}</p><h2 id="info-title">${d.title}</h2>${d.body}${d.start?`<button class="button info-cta" data-info-start="${d.start}">Darüber möchte ich sprechen</button>`:''}`;infoDialog.showModal();document.body.classList.add('modal-open');}
function closeInfo(){infoDialog.close();if(!flowDialog.open)document.body.classList.remove('modal-open');}
infoDialog.addEventListener('close',()=>{if(!flowDialog.open)document.body.classList.remove('modal-open');});
document.querySelector('[data-close-info]').addEventListener('click',closeInfo);

const flowDialog=document.querySelector('#consultation');
const flowRoot=document.querySelector('#flow-root');
const emptyState=()=>({occasion:'',burial:'',farewell:'',priorities:[],notes:'',mode:'Telefonisch',time:'Ganz flexibel',date:'',name:'',contact:'',consent:false});
let state=emptyState(),step=0,completed=false,returnFocus=null;
const stepLabels=['Ihr Anliegen','Die Bestattungsform','Der Abschied','Ihre Wünsche','Unser Gespräch','Ihr Überblick'];
const stepContent=[
 {label:'ERST EINMAL ANKOMMEN',title:'Was führt Sie zu uns?',description:'Wir holen Sie dort ab, wo Sie gerade stehen.',field:'occasion',options:[['Ein Mensch ist verstorben','Ich brauche jetzt Unterstützung.','heart'],['Ich möchte vorsorgen','Ich möchte meine eigenen Wünsche festhalten.','leaf'],['Ich möchte mich informieren','Ich brauche erst einmal Orientierung.','chat']]},
 {label:'ES GIBT KEINE FALSCHE ANTWORT',title:'Welche Form kommt für Sie infrage?',description:'Eine erste Richtung genügt. Baum- und Seebestattungen setzen eine Einäscherung voraus. Ihre Wünsche können Sie später ändern.',field:'burial',options:[['Erdbestattung','Beisetzung im Sarg auf einem Friedhof.','sun'],['Feuerbestattung','Beisetzung einer Urne auf einem Friedhof.','heart'],['Baumbestattung','Eine Urne am Fuße eines Baumes.','leaf'],['Seebestattung','Eine Urne wird dem Meer übergeben.','waves'],['Ich weiß es noch nicht','Ich möchte die Möglichkeiten gemeinsam besprechen.','chat']]},
 {label:'RAUM FÜR ERINNERUNGEN',title:'Wie stellen Sie sich den Abschied vor?',description:'Das ist ein erster Gedanke, noch keine Entscheidung.',field:'farewell',options:[['Im engsten Kreis','Ein persönlicher Abschied mit wenigen vertrauten Menschen.','heart'],['Mit Familie und Freunden','Gemeinsam erinnern und Abschied nehmen.','home'],['Ohne Trauerfeier','Ein stiller Abschied ohne gemeinsame Feier.','leaf'],['Das möchte ich noch offenlassen','Wir finden im Gespräch heraus, was passt.','chat']]}
];
function startFlow(occasion){returnFocus=document.activeElement;if(completed){state=emptyState();completed=false;step=0;}if(occasion==='trauerfall'){state.occasion='Ein Mensch ist verstorben';step=1;}else if(occasion==='vorsorge'){state.occasion='Ich möchte vorsorgen';step=1;}document.querySelector('#mobile-nav').hidden=true;menuButton.setAttribute('aria-expanded','false');renderFlow(false);if(!flowDialog.open)flowDialog.showModal();document.body.classList.add('modal-open');}
function closeFlow(){flowDialog.close();}
flowDialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');returnFocus?.focus();});
function optionCards(d){return `<fieldset class="options"><legend class="sr-only">${d.title}</legend>${d.options.map(([title,desc,i])=>`<label class="choice ${state[d.field]===title?'is-selected':''}"><input type="radio" name="${d.field}" value="${escapeHTML(title)}" ${state[d.field]===title?'checked':''}>${d.field==='burial'&&Object.values(burialImages).find(img=>img.name===title)?`<img class="choice-macro" src="${Object.values(burialImages).find(img=>img.name===title).src}" alt="" width="80" height="80">`:icon(i)}<span><strong>${title}</strong><small>${desc}</small></span><span class="choice-check" aria-hidden="true"></span></label>`).join('')}</fieldset>`;}
function summaryRows(){return [['Ihr Anliegen',state.occasion,0],['Bestattungsform',state.burial,1],['Abschied',state.farewell,2],['Was Ihnen wichtig ist',state.priorities.join(', ')||'Im Gespräch klären',3],['Ihre Gedanken',state.notes||'Keine zusätzlichen Angaben',3],['Gesprächswunsch',`${state.mode} · ${state.time}${state.date?' · '+formatDate(state.date):''}`,4],['Kontakt',`${state.name} · ${state.contact}`,4]];}
function formatDate(value){const d=new Date(value+'T12:00:00');return Number.isNaN(d.getTime())?value:d.toLocaleDateString('de-DE',{day:'numeric',month:'long',year:'numeric'});}
function localToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function renderStep(){
 if(step<3){const d=stepContent[step];return `<p class="eyebrow">${d.label}</p><h2 id="flow-title" tabindex="-1">${d.title}</h2><p class="flow-description">${d.description}</p>${optionCards(d)}${step===0?'<p class="gentle-note">Bei einem akuten Trauerfall sind wir auch direkt unter <a href="tel:+49203582448">0203 / 58 24 48</a> erreichbar.</p>':''}`;}
 if(step===3)return `<p class="eyebrow">DAS PERSÖNLICHE ZÄHLT</p><h2 id="flow-title" tabindex="-1">Was liegt Ihnen am Herzen?</h2><p class="flow-description">Wählen Sie, was Sie bewegt. Sie dürfen diesen Schritt auch offenlassen.</p><fieldset class="priority-options"><legend class="sr-only">Ihre Wünsche, Mehrfachauswahl möglich</legend>${['Eine persönliche Trauerfeier','Verbundenheit mit der Natur','Die Kosten im Blick behalten','Wenig Aufwand für die Grabpflege','Religiöse oder kulturelle Wünsche','Entlastung bei Formalitäten'].map(v=>`<label class="priority-choice"><input type="checkbox" name="priority" value="${v}" ${state.priorities.includes(v)?'checked':''}><span>${v}</span></label>`).join('')}</fieldset><label class="field-label" for="notes">Möchten Sie uns etwas mitgeben? <small>Optional</small></label><textarea id="notes" maxlength="500" rows="3" placeholder="Ein Wunsch, eine Frage oder etwas, das wir wissen sollten …">${escapeHTML(state.notes)}</textarea><p class="field-note">Für diese Vorschau bitte keine vertraulichen Angaben eintragen.</p>`;
 if(step===4)return `<p class="eyebrow">PERSÖNLICH WEITERGEHEN</p><h2 id="flow-title" tabindex="-1">Wie möchten Sie mit uns sprechen?</h2><p class="flow-description">Ihr Gesprächswunsch. Ein Termin würde anschließend persönlich bestätigt.</p><div class="demo-inline">Pitch-Vorschau · Bitte nur Beispieldaten verwenden. Kein Versand.</div><form id="contact-form"><fieldset class="mode-options"><legend class="field-label">Gesprächsform</legend>${['Telefonisch','Im Bestattungshaus','Bei mir zu Hause'].map(v=>`<label><input type="radio" name="mode" value="${v}" ${state.mode===v?'checked':''}><span>${v}</span></label>`).join('')}</fieldset><div class="field-row"><div><label class="field-label" for="contact-time">Wann passt es Ihnen?</label><select id="contact-time">${['Ganz flexibel','Vormittags','Nachmittags'].map(v=>`<option ${state.time===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label class="field-label" for="contact-date">Wunschtag <small>Optional</small></label><input type="date" id="contact-date" min="${localToday()}" value="${escapeHTML(state.date)}"></div></div><label class="field-label" for="contact-name">Ihr Name</label><input id="contact-name" name="name" autocomplete="off" required maxlength="100" value="${escapeHTML(state.name)}" placeholder="z. B. Alex Beispiel"><label class="field-label" for="contact-value">E-Mail-Adresse oder Telefonnummer</label><input id="contact-value" name="contact" autocomplete="off" required maxlength="150" value="${escapeHTML(state.contact)}" placeholder="z. B. alex@example.com"><label class="consent"><input type="checkbox" id="contact-consent" ${state.consent?'checked':''} required><span>Ich habe verstanden, dass dies eine Vorschau ist und meine Angaben nicht versendet werden.</span></label><p id="form-error" role="alert" class="form-error"></p></form>`;
 return `<p class="eyebrow">ALLES DARF NOCH OFFEN SEIN</p><h2 id="flow-title" tabindex="-1">Ihre Wünsche. Auf einen Blick.</h2><p class="flow-description">Sie können alles noch einmal ändern. Daraus entsteht die Grundlage für ein persönliches Gespräch.</p><dl class="summary-list">${summaryRows().map(([label,value,idx])=>`<div><dt>${label}</dt><dd>${escapeHTML(value)}</dd><button class="inline-button" data-edit="${idx}" aria-label="${label} ändern">Ändern</button></div>`).join('')}</dl><div class="demo-inline">Dies ist ein Pitch: Der nächste Klick zeigt den beispielhaften Abschluss. Es wird keine Anfrage versendet und kein Termin reserviert.</div>`;
}
function renderFlow(focus=true){
 flowRoot.innerHTML=`<button class="close-button" data-close-flow aria-label="Gesprächsvorbereitung schließen">×</button><div class="flow-layout"><aside class="flow-sidebar"><a class="flow-brand" href="#" data-close-flow>Kretschmer<span>AN IHRER SEITE.</span></a><p class="sidebar-title">Wir nehmen uns<br><em>Zeit für Sie.</em></p><ol>${stepLabels.map((s,i)=>`<li class="${completed||i<step?'is-done':i===step?'is-current':''}" ${i===step?'aria-current="step"':''}><span>${completed||i<step?'✓':String(i+1).padStart(2,'0')}</span>${s}</li>`).join('')}</ol><div class="sidebar-bottom">${icon('shield')}<p>Ihre Gedanken bleiben in dieser Vorschau auf Ihrem Gerät.</p></div></aside><div class="flow-main">${completed?renderComplete():`<div class="flow-status"><span>Schritt ${step+1} von 6</span><span>In Ihrem Tempo.</span></div><progress value="${step+1}" max="6" aria-label="Fortschritt"></progress><div class="flow-step">${renderStep()}</div><div class="flow-bottom"><button class="text-button back-button" data-back>${step===0?'Schließen':'Zurück'}</button><button class="button" data-next ${step<3&&!state[stepContent[step].field]?'disabled':''}>${step===5?'Abschluss im Pitch ansehen':step===4?'Zusammenfassung ansehen':'Weiter'}</button></div>`}</div></div>`;
 flowDialog.scrollTop=0;
 if(focus)document.querySelector('#flow-title')?.focus({preventScroll:true});
}
function renderComplete(){return `<div class="completion"><span class="completion-icon">${icon('check')}</span><p class="eyebrow">DER ERSTE SCHRITT IST GEMACHT</p><h2 id="flow-title" tabindex="-1">Ein wenig mehr Klarheit.<br><em>Für den nächsten Schritt.</em></h2><p>Ihre Gesprächsvorbereitung ist fertig. Sie können Ihre Wünsche jetzt speichern und zu einem persönlichen Gespräch mitnehmen.</p><div class="completion-notice"><strong>Vorschau abgeschlossen – nichts versendet.</strong><p>Es wurde kein Termin gebucht. Für echte Unterstützung erreichen Sie Kretschmer unter <a href="tel:+49203582448">0203 / 58 24 48</a>.</p></div><button class="button" data-download>Meine Zusammenfassung speichern</button><button class="text-button" data-review>Zusammenfassung noch einmal ansehen</button><button class="inline-button reset-button" data-reset>Angaben löschen & neu beginnen</button></div>`;}
function collectContact(){state.mode=flowRoot.querySelector('[name="mode"]:checked')?.value||'Telefonisch';state.time=flowRoot.querySelector('#contact-time').value;state.date=flowRoot.querySelector('#contact-date').value;state.name=flowRoot.querySelector('#contact-name').value.trim();state.contact=flowRoot.querySelector('#contact-value').value.trim();state.consent=flowRoot.querySelector('#contact-consent').checked;}
function validateContact(){collectContact();const name=flowRoot.querySelector('#contact-name'),contact=flowRoot.querySelector('#contact-value'),date=flowRoot.querySelector('#contact-date');name.setCustomValidity(state.name.length<2?'Bitte geben Sie einen Namen mit mindestens zwei Zeichen an.':'');const validContact=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.contact)||(/^[+()\d\s./-]+$/.test(state.contact)&&state.contact.replace(/\D/g,'').length>=6);contact.setCustomValidity(validContact?'':'Bitte geben Sie eine gültige E-Mail-Adresse oder Telefonnummer ein.');date.setCustomValidity(state.date&&state.date<localToday()?'Bitte wählen Sie heute oder einen zukünftigen Tag.':'');const form=flowRoot.querySelector('#contact-form');if(!form.reportValidity()){flowRoot.querySelector('#form-error').textContent='Bitte prüfen Sie die markierten Angaben.';return false;}return true;}
function downloadSummary(){const lines=['KRETSCHMER – PERSÖNLICHE GESPRÄCHSVORBEREITUNG','Pitch-Vorschau: Keine Anfrage versendet. Kein Termin gebucht.','',...summaryRows().map(([k,v])=>`${k}: ${v}`),'','Kontakt: 0203 / 58 24 48','Originalwebsite: https://www.kretschmer-duisburg.de/'];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Kretschmer-Gespraechsvorbereitung.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
flowRoot.addEventListener('change',e=>{const t=e.target;if(t.matches('input[type="radio"]')&&step<3){state[stepContent[step].field]=t.value;flowRoot.querySelectorAll('.choice').forEach(el=>el.classList.toggle('is-selected',el.querySelector('input').checked));flowRoot.querySelector('[data-next]').disabled=false;}if(t.name==='priority')state.priorities=[...flowRoot.querySelectorAll('[name="priority"]:checked')].map(v=>v.value);if(step===4)collectContact();});
flowRoot.addEventListener('input',e=>{if(e.target.id==='notes')state.notes=e.target.value;if(step===4){e.target.setCustomValidity?.('');collectContact();}});
flowRoot.addEventListener('submit',e=>{e.preventDefault();if(step===4&&validateContact()){step=5;renderFlow();}});
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;
 if(el.hasAttribute('data-start'))startFlow(el.dataset.start);
 if(el.hasAttribute('data-info'))showInfo(el.dataset.info);
 if(el.hasAttribute('data-info-start')){const v=el.dataset.infoStart;closeInfo();startFlow();if(v!=='offen'){state.burial=v;step=state.occasion?2:0;renderFlow();}}
 if(el.hasAttribute('data-close-flow')){e.preventDefault();closeFlow();}
 if(el.hasAttribute('data-back')){if(step===4)collectContact();if(step===0)closeFlow();else{step--;renderFlow();}}
 if(el.hasAttribute('data-next')){if(step<3&&!state[stepContent[step].field])return;if(step===4&&!validateContact())return;if(step===5)completed=true;else step++;renderFlow();}
 if(el.hasAttribute('data-edit')){step=Number(el.dataset.edit);renderFlow();}
 if(el.hasAttribute('data-download'))downloadSummary();
 if(el.hasAttribute('data-review')){completed=false;step=5;renderFlow();}
 if(el.hasAttribute('data-reset')){state=emptyState();step=0;completed=false;renderFlow();}
});

// Progressive enhancement for browsers implementing the proposed WebMCP registry.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'start_conversation_preparation',title:'Gesprächsvorbereitung öffnen',description:'Open the local consultation preview. Does not submit personal data or book an appointment.',inputSchema:{type:'object',properties:{occasion:{type:'string',enum:['trauerfall','vorsorge','orientierung']}},required:['occasion'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!['trauerfall','vorsorge','orientierung'].includes(input.occasion))throw new Error('Invalid occasion');startFlow(input.occasion);return{opened:flowDialog.open,step:step+1,submitted:false};}})).catch(()=>{});}catch{}}
menuButton.addEventListener('click',()=>{document.querySelector('#mobile-nav').style.top=document.querySelector('.site-header').getBoundingClientRect().bottom+'px';});
